allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  esbuild: true
  vue-demi: true
onlyBuiltDependencies:
  - '@weapp-tailwindcss/merge'
minimumReleaseAge: 0
patchedDependencies:
  weapp-tailwindcss@5.1.11: patches/weapp-tailwindcss@5.1.11.patch
